# This file represents the default values when a customer has not filled them out
coverage:
  precision: 2
  round: down
  range: "10...100"

  notify:
    require_ci_to_pass: yes

  status:
    project: yes
    patch: yes
    changes: yes

comment:
  layout: "header, diff, changes"
  behavior: default